return {
  require("diddado.plugins.dashboard-vim"),
  require("diddado.plugins.disabled"),
  require("diddado.plugins.flash"),
  require("diddado.plugins.golang"),
  require("diddado.plugins.harpoon"),
  require("diddado.plugins.minitest"),
  require("diddado.plugins.neo-tree"),
  require("diddado.plugins.neotest"),
  require("diddado.plugins.snacks"),
  require("diddado.plugins.tailwind"),
  require("diddado.plugins.telescope-file-browser"),
  require("diddado.plugins.telescope-undo"),
  require("diddado.plugins.theme"),
  require("diddado.plugins.vim-coffee-script"),
  -- require("diddado.plugins.vim-tmux-navigator"),
  require("diddado.plugins.window-picker"),

  -- require("diddado.plugins.disable-compiler-plugins"),
}
